# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.define "chefworkstation01" do |machine|
    hostname = "chefworkstation01"
    machine.vm.hostname = hostname
    machine.vm.network "public_network", ip: "10.0.0.102",
      :netmask => '255.255.0.0'
    machine.vm.provider "virtualbox" do |vbox|
      vbox.name = "chefworkstation01"
    end
  end
  
  config.vm.provision :shell, path: "bootstrap.sh"
end
